version: '3'
services: 
    web:
        build: ./chatbot-api
        ports:
            - "5000:5000"
        volumes:
            - ./chatbot-api:/app
    react:
        stdin_open: true
        build: ./chatbot-web
        ports:
            - "3000:3000"
        container_name: chatbot-web
        volumes: 
            - /app/node_modules
            - ./chatbot-web:/app