version: '3'
services: 
    web:
        build: ./server
        ports:
            - "5000:5000"
        volumes:
            - ./server:/app
    react:
        stdin_open: true
        build: ./web
        ports:
            - "3000:3000"
        container_name: web
        volumes: 
            - /app/node_modules
            - ./web:/app